# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='password',
        ),
        migrations.RemoveField(
            model_name='hostname',
            name='username',
        ),
    ]
